name: main_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^0.8.5+3 
  fluttertoast: ^8.0.9

flutter:
  uses-material-design: true
  assets:
    
    - assets/act.png
    - assets/example/
    - assets/city/
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/img4.jpg
    - assets/img5.jpg
    - assets/mumbai.jpg
    - assets/nagpur.jpg
    - assets/virat.jpg
    - assets/wed.jpg
    - assets/ass1/
    - assets/logo.jpg
    - assets/wrapper.png
    - assets/a.jpg
    - assets/c.jpg
    - assets/e.jpg
    - assets/b.jpeg
    - assets/m.jpeg
    - assets/h.jpeg
    - assets/s.jpeg
    - assets/d.jpeg
    - assets/carnival.jpg
    - assets/AA.jpg
    - assets/BBB.jpg
    - assets/DDD.jpg
    - assets/CCC.jpg
    - assets/birthday/b1/
    - assets/engagement/e1/
    - assets/guzzle/g1/
    - assets/phonepay.png
    - assets/paytm.png
    - assets/gpay.png
    

